W-13673062: Update to Java 17
mulesoft/api_project_maven_client pull request #75
Opened 2023-07-26 20:54 UTC by tomasperezc

- Moved from JDK8 to JDK17
- Updated to build with Maven Wrapper 3.9.3
- Updated Ubuntu image to 22.04
- Updated `jackson-databind` to 2.13.5 (See (PR#73)[https://github.com/mulesoft/api_project_maven_client/pull/72])
- Set `maven-compiler-plugin` 3.11.0 at root pom, and remove redundant configuration in `polyglot-exchange`
- Bump to release version 2.3.0

2023-07-26 23:22 UTC, mdaloia requested changes

2023-07-26 23:22 UTC, mdaloia commented on pom.xml
> +                        </properties>
The `source`, `target` and `release` go directly under `configuration`:
https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html

2023-07-27 13:18 UTC, merged

2023-07-27 13:34 UTC, marinarv commented
Hello guys! I would suggest to release this lib with a change in the major version. ACB is not using java 17 in the short time and if we need to add some change which also required a release we will need to branch from this point (now there is not a special requirement but it could happen during the time we are not updated to java 17). Make sense?
@mdaloia @tomasperezc

2023-07-27 13:37 UTC, mdaloia commented
> Hello guys! I would suggest to release this lib with a change in the major version. ACB is not using java 17 in the short time and if we need to add some change which also required a release we will need to branch from this point (now there is not a special requirement but it could happen during the time we are not updated to java 17). Make sense? @mdaloia @tomasperezc

@marinarv we are not dropping support to Java 8 or 11... in fact we are compiling with source, target and release using language level 1.8.... that is the reason why we didn't released a major version.
You shouldn't face any issue using it with 8 or 11... let us know if you found some issues.

2023-07-27 13:41 UTC, marinarv commented
> 

If that is the case we are ok! Thank you!